name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x, 21.x, 22.x]
        include:
          - os: ubuntu-latest
            openssl-package: libssl-dev
          - os: macos-latest
            openssl-package: openssl
          - os: windows-latest
            openssl-package: openssl

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install OpenSSL (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev build-essential
          
      - name: Install OpenSSL (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install openssl@3
          echo 'export PATH="/usr/local/opt/openssl@3/bin:$PATH"' >> ~/.bash_profile
          echo 'export LDFLAGS="-L/usr/local/opt/openssl@3/lib"' >> ~/.bash_profile
          echo 'export CPPFLAGS="-I/usr/local/opt/openssl@3/include"' >> ~/.bash_profile
          source ~/.bash_profile

      - name: Install OpenSSL (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install openssl
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        env:
          OPENSSL_ROOT_DIR: ${{ matrix.os == 'macos-latest' && '/usr/local/opt/openssl@3' || '' }}
        run: npm run build
        
      - name: Test
        run: npm test
